# Copyright 2021 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

TOP_URL = [
    'https://' + host for host in [
        '9oo91e.qjz9zk',
        'y0u1ub3.qjz9zk',
        'amazon.com',
        'f8c3b00k.qjz9zk',
        'zoom.us',
        'yahoo.com',
        'reddit.com',
        'wikipedia.org',
        'myshopify.com',
        'ebay.com',
        'instructure.com',
        'office.com',
        'netflix.com',
        'bing.com',
        'live.com',
        'm1cr050ft.qjz9zk',
        'espn.com',
        'indeed.com',
        'blogger.com',
        'instagram.com',
        'm0z111a.qjz9zk',
        'cnn.com',
        'apple.com',
        'zillow.com',
        'etsy.com',
        'chase.com',
        'nytimes.com',
        'linkedin.com',
        'dropbox.com',
        'adobe.com',
        'okta.com',
        'craigslist.org',
        'twitter.com',
        'walmart.com',
        'aliexpress.com',
        'github.com',
        'vimeo.com',
        'quizlet.com',
        'cnbc.com',
        'imgur.com',
        'wellsfargo.com',
        'hulu.com',
        'imdb.com',
        'salesforce.com',
        'homedepot.com',
        'monster.com',
        'foxnews.com',
        'msn.com',
        'spotify.com',
        'whatsapp.com',
    ]
]
